"""Add budget tracking models and enhancements

Revision ID: 4b205cdf4527
Revises: 02b213f9bfa8
Create Date: 2025-11-09 08:30:06.593963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b205cdf4527'
down_revision = '02b213f9bfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_user_alerts', ['user_id', 'is_read'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budget_period', ['user_id', 'category_id', 'year', 'month'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_threshold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_budget', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_budget')
        batch_op.drop_column('monthly_income')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('alert_threshold')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budget_period')

    op.drop_table('budgets')
    with op.batch_alter_table('budget_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_user_alerts')

    op.drop_table('budget_alerts')
    # ### end Alembic commands ###
